### ISSUE TITLE
crash meeting list

### ISSUE THREAD

**Issue by lukio** [gcoop-libre/cooperative_ar#19]
Version: 3.8

```python
Traceback (most recent call last):
  File "/home/lukio/tryton-dist/tryton-dev/tryton/gui/window/view_form/view/screen_container.py", line 524, in search_box
    entry.connect_activate(lambda *a: search())
  File "/home/lukio/tryton-dist/tryton-dev/tryton/gui/window/view_form/view/screen_container.py", line 65, in connect_activate
    widget.child.connect('activate', callback)
AttributeError: 'gtk.Entry' object has no attribute 'child'
```

**Comment by lukio** [comment]
How to reproduce?
1. Open meeting list view
2. Click filter button

**Comment by lukio** [comment]
I believe this is a tryton-client bug. For now I will remove those fields from the listview.
